export const CREATE_CHAT_SUCCESS = 'CREATE_CHAT_SUCCESS';
export const CREATE_CHAT_FAIL = 'CREATE_CHAT_FAIL';

export const GET_CHAT_LIST_REQUEST = 'GET_CHAT_LIST_REQUEST';
export const GET_CHAT_LIST_SUCCESS = 'GET_CHAT_LIST_SUCCESS';
export const GET_CHAT_LIST_FAIL = 'GET_CHAT_LIST_FAIL';

// export const SEND_MESSAGE_REQUEST = 'SEND_MESSAGE_REQUEST';
// export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
// export const SEND_MESSAGE_FAIL = 'SEND_MESSAGE_FAIL';

export const GET_CHAT_HISTORY_REQUEST = 'GET_CHAT_HISTORY_REQUEST';
export const GET_CHAT_HISTORY_SUCCESS = 'GET_CHAT_HISTORY_SUCCESS';
export const GET_CHAT_HISTORY_FAIL = 'GET_CHAT_HISTORY_FAIL';

export const LOAD_MORE_MESSAGES_REQUEST = 'LOAD_MORE_MESSAGES_REQUEST';
export const LOAD_MORE_MESSAGES_SUCCESS = 'LOAD_MORE_MESSAGES_SUCCESS';
export const LOAD_MORE_MESSAGES_FAIL = 'LOAD_MORE_MESSAGES_FAIL';


export const CLEAR_CHAT = 'CLEAR_CHAT';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
