export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_FAIL = "LOAD_USER_FAIL";

export const COMPLETE_PROFILE_REQUEST = "COMPLETE_PROFILE_REQUEST";
export const COMPLETE_PROFILE_SUCCESS = "COMPLETE_PROFILE_SUCCESS";
export const COMPLETE_PROFILE_FAIL = "COMPLETE_PROFILE_FAIL";

export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL";
export const UPDATE_PROFILE_RESET = "UPDATE_PROFILE_RESET";

export const CHANGE_PASSWORD_REQUEST = "CHANGE_PASSWORD_REQUEST";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAIL = "CHANGE_PASSWORD_FAIL";
export const CHANGE_PASSWORD_RESET = "CHANGE_PASSWORD_RESET";

export const CREATE_PROBLEM_REQUEST = "CREATE_PROBLEM_REQUEST";
export const CREATE_PROBLEM_SUCCESS = "CREATE_PROBLEM_SUCCESS";
export const CREATE_PROBLEM_FAIL = "CREATE_PROBLEM_FAIL";
export const CREATE_PROBLEM_RESET = "CREATE_PROBLEM_RESET";

export const DELETE_PROBLEM_SUCCESS = "DELETE_PROBLEM_SUCCESS";
export const DELETE_PROBLEM_FAIL = "DELETE_PROBLEM_FAIL";

export const CHANGE_PROBLEM_STATUS_SUCCESS = "CHANGE_PROBLEM_STATUS_SUCCESS";
export const CHANGE_PROBLEM_STATUS_FAIL = "CHANGE_PROBLEM_STATUS_FAIL";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

export const ADD_SKILL_REQUEST = "ADD_SKILL_REQUEST";
export const ADD_SKILL_SUCCESS = "ADD_SKILL_SUCCESS";
export const ADD_SKILL_FAIL = "ADD_SKILL_FAIL";
export const ADD_SKILL_RESET = "ADD_SKILL_RESET";

export const LOAD_OTHER_USER_REQUEST = "LOAD_OTHER_USER_REQUEST";
export const LOAD_OTHER_USER_SUCCESS = "LOAD_OTHER_USER_SUCCESS";
export const LOAD_OTHER_USER_FAIL = "LOAD_OTHER_USER_FAIL";

export const NEARBY_USER_REQUEST = 'NEARBY_USER_REQUEST';
export const NEARBY_USER_SUCCESS = 'NEARBY_USER_SUCCESS';
export const NEARBY_USER_FAIL = 'NEARBY_USER_FAIL';

export const CREATE_REVIEW_REQUEST = 'CREATE_REVIEW_REQUEST';
export const CREATE_REVIEW_SUCCESS = 'CREATE_REVIEW_SUCCESS';
export const CREATE_REVIEW_FAIL = 'CREATE_REVIEW_FAIL';

export const APPLY_PROBLEM_REQUEST = 'APPLY_PROBLEM_REQUEST';
export const APPLY_PROBLEM_SUCCESS = 'APPLY_PROBLEM_SUCCESS';
export const APPLY_PROBLEM_FAIL = 'APPLY_PROBLEM_FAIL';

export const GET_USER_PROBLEM_DETAILS_REQUEST = 'GET_USER_PROBLEM_DETAILS_REQUEST';
export const GET_USER_PROBLEM_DETAILS_SUCCESS = 'GET_USER_PROBLEM_DETAILS_SUCCESS';
export const GET_USER_PROBLEM_DETAILS_FAIL = 'GET_USER_PROBLEM_DETAILS_FAIL';

export const ADD_NOTIFICATION_REQUEST = 'ADD_NOTIFICATION_REQUEST';
export const ADD_NOTIFICATION_SUCCESS = 'ADD_NOTIFICATION_SUCCESS';
export const ADD_NOTIFICATION_FAIL = 'ADD_NOTIFICATION_FAIL';

export const FETCH_NOTIFICATIONS_REQUEST = 'FETCH_NOTIFICATIONS_REQUEST';
export const FETCH_NOTIFICATIONS_SUCCESS = 'FETCH_NOTIFICATIONS_SUCCESS';
export const FETCH_NOTIFICATIONS_FAIL = 'FETCH_NOTIFICATIONS_FAIL';

export const REJECT_NOTIFICATION_REQUEST = 'REJECT_NOTIFICATION_REQUEST';
export const REJECT_NOTIFICATION_SUCCESS = 'REJECT_NOTIFICATION_SUCCESS';
export const REJECT_NOTIFICATION_FAIL = 'REJECT_NOTIFICATION_FAIL';

export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAIL = "FORGOT_PASSWORD_FAIL";

export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";


export const ALL_USERS_REQUEST = "ALL_USERS_REQUEST";
export const ALL_USERS_SUCCESS = "ALL_USERS_SUCCESS";
export const ALL_USERS_FAIL = "ALL_USERS_FAIL";

export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_RESET = "UPDATE_USER_RESET";
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL";

export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";
export const DELETE_USER_RESET = "DELETE_USER_RESET";

export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const CLEAR_MESSAGES = "CLEAR_MESSAGES";